services:
  - type: web
    name: pothole-detection-webapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run webapp.py --server.port $PORT --server.address 0.0.0.0"
    plan: free
