/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117763-ge35587250c-20241113"
#endif /* AVUTIL_FFVERSION_H */
